
codon_table_list = ['TTT','TTC','TTA','TTG','TCT','TCC','TCA','TCG','TAT','TAC','TAA',
                    'TAG','TGT','TGC','TGA','TGG','CTT','CTC','CTA','CTG','CCT','CCC',
                    'CCA','CCG','CAT','CAC','CAA','CAG','CGT','CGC','CGA','CGG','ATT',
                    'ATC','ATA','ATG','ACT','ACC','ACA','ACG','AAT','AAC','AAA','AAG',
                    'AGT','AGC','AGA','AGG','GTT','GTC','GTA','GTG','GCT','GCC','GCA',
                    'GCG','GAT','GAC','GAA','GAG','GGT','GGC','GGA','GGG']

multibox_codon_table_list = ['TTT', 'TTC', 'TTA', 'TTG', 'TCT', 'TCC', 'TCA', 'TCG', 'TAT', 'TAC', 
                             'TGT', 'TGC', 'CTT', 'CTC', 'CTA', 'CTG', 'CCT', 'CCC', 'CCA', 'CCG', 
                             'CAT', 'CAC', 'CAA', 'CAG', 'CGT', 'CGC', 'CGA', 'CGG', 'ATT', 'ATC', 
                             'ATA', 'ACT', 'ACC', 'ACA', 'ACG', 'AAT', 'AAC', 'AAA', 'AAG', 'AGT', 
                             'AGC', 'AGA', 'AGG', 'GTT', 'GTC', 'GTA', 'GTG', 'GCT', 'GCC', 'GCA', 
                             'GCG', 'GAT', 'GAC', 'GAA', 'GAG', 'GGT', 'GGC', 'GGA', 'GGG']

translation_aa_codon_dict = {'S':['TCT','TCC','TCA','TCG','AGT','AGC'], 
                             'R':['CGT','CGC','CGA','CGG','AGA','AGG'],
                             'L':['CTT','CTC','CTA','CTG','TTA','TTG'], 
                             'A':['GCT','GCC','GCA','GCG'],
                             'G':['GGT','GGC','GGA','GGG'], 
                             'P':['CCT','CCC','CCA','CCG'], 
                             'T':['ACT','ACC','ACA','ACG'],
                             'V':['GTT','GTC','GTA','GTG'], 
                             'I':['ATT','ATC','ATA'], 
                             'F':['TTT','TTC'],
                             'N':['AAT','AAC'], 
                             'D':['GAT','GAC'], 
                             'H':['CAT','CAC'], 
                             'C':['TGT','TGC'],
                             'Y':['TAT','TAC'], 
                             'Q':['CAA','CAG'], 
                             'K':['AAA','AAG'], 
                             'E':['GAA','GAG'],
                             'M':['ATG'], 
                             'W':['TGG'], 
                             '*':['TAA','TAG','TGA']}

codon_codon_box_dict_numeric = {'TTT': 2, 'TTC': 2, 'TTA': 6, 'TTG': 6, 'TCT': 6,
                                'TCC': 6, 'TCA': 6, 'TCG': 6, 'TAT': 2, 'TAC': 2,
                                'TAA': 3, 'TAG': 3, 'TGT': 2, 'TGC': 2, 'TGA': 3,
                                'TGG': 1, 'CTT': 6, 'CTC': 6, 'CTA': 6, 'CTG': 6,
                                'CCT': 4, 'CCC': 4, 'CCA': 4, 'CCG': 4, 'CAT': 2,
                                'CAC': 2, 'CAA': 2, 'CAG': 2, 'CGT': 6, 'CGC': 6,
                                'CGA': 6, 'CGG': 6, 'ATT': 3, 'ATC': 3, 'ATA': 3,
                                'ATG': 1, 'ACT': 4, 'ACC': 4, 'ACA': 4, 'ACG': 4,
                                'AAT': 2, 'AAC': 2, 'AAA': 2, 'AAG': 2, 'AGT': 6,
                                'AGC': 6, 'AGA': 6, 'AGG': 6, 'GTT': 4, 'GTC': 4,
                                'GTA': 4, 'GTG': 4, 'GCT': 4, 'GCC': 4, 'GCA': 4,
                                'GCG': 4, 'GAT': 2, 'GAC': 2, 'GAA': 2, 'GAG': 2,
                                'GGT': 4, 'GGC': 4, 'GGA': 4, 'GGG': 4}

no_stop_codon_mutation_table_list = [
    'TTT->ATT', 'TTT->GTT', 'TTT->CTT', 'TTT->TAT', 'TTT->TGT', 'TTT->TCT', 'TTT->TTA', 'TTT->TTG', 'TTT->TTC', 'TTC->ATC', 'TTC->GTC', 'TTC->CTC', 'TTC->TAC', 'TTC->TGC', 'TTC->TCC', 'TTC->TTA', 'TTC->TTT', 'TTC->TTG', 'TTA->ATA',
    'TTA->GTA', 'TTA->CTA', 'TTA->TCA', 'TTA->TTT', 'TTA->TTG', 'TTA->TTC', 'TTG->ATG', 'TTG->GTG', 'TTG->CTG', 'TTG->TGG', 'TTG->TCG', 'TTG->TTA', 'TTG->TTT', 'TTG->TTC', 'TCT->ACT', 'TCT->GCT', 'TCT->CCT', 'TCT->TAT', 'TCT->TTT',
    'TCT->TGT', 'TCT->TCA', 'TCT->TCG', 'TCT->TCC', 'TCC->ACC', 'TCC->GCC', 'TCC->CCC', 'TCC->TAC', 'TCC->TTC', 'TCC->TGC', 'TCC->TCA', 'TCC->TCT', 'TCC->TCG', 'TCA->ACA', 'TCA->GCA', 'TCA->CCA', 'TCA->TTA', 'TCA->TCT', 'TCA->TCG',
    'TCA->TCC', 'TCG->ACG', 'TCG->GCG', 'TCG->CCG', 'TCG->TTG', 'TCG->TGG', 'TCG->TCA', 'TCG->TCT', 'TCG->TCC', 'TAT->AAT', 'TAT->GAT', 'TAT->CAT', 'TAT->TTT', 'TAT->TGT', 'TAT->TCT', 'TAT->TAC', 'TAC->AAC', 'TAC->GAC', 'TAC->CAC',
    'TAC->TTC', 'TAC->TGC', 'TAC->TCC', 'TAC->TAT', 'TGT->AGT', 'TGT->GGT', 'TGT->CGT', 'TGT->TAT', 'TGT->TTT', 'TGT->TCT', 'TGT->TGG', 'TGT->TGC', 'TGC->AGC', 'TGC->GGC', 'TGC->CGC', 'TGC->TAC', 'TGC->TTC', 'TGC->TCC', 'TGC->TGT',
    'TGC->TGG', 'TGG->AGG', 'TGG->GGG', 'TGG->CGG', 'TGG->TTG', 'TGG->TCG', 'TGG->TGT', 'TGG->TGC', 'CTT->ATT', 'CTT->TTT', 'CTT->GTT', 'CTT->CAT', 'CTT->CGT', 'CTT->CCT', 'CTT->CTA', 'CTT->CTG', 'CTT->CTC', 'CTC->ATC', 'CTC->TTC',
    'CTC->GTC', 'CTC->CAC', 'CTC->CGC', 'CTC->CCC', 'CTC->CTA', 'CTC->CTT', 'CTC->CTG', 'CTA->ATA', 'CTA->TTA', 'CTA->GTA', 'CTA->CAA', 'CTA->CGA', 'CTA->CCA', 'CTA->CTT', 'CTA->CTG', 'CTA->CTC', 'CTG->ATG', 'CTG->TTG', 'CTG->GTG',
    'CTG->CAG', 'CTG->CGG', 'CTG->CCG', 'CTG->CTA', 'CTG->CTT', 'CTG->CTC', 'CCT->ACT', 'CCT->TCT', 'CCT->GCT', 'CCT->CAT', 'CCT->CTT', 'CCT->CGT', 'CCT->CCA', 'CCT->CCG', 'CCT->CCC', 'CCC->ACC', 'CCC->TCC', 'CCC->GCC', 'CCC->CAC',
    'CCC->CTC', 'CCC->CGC', 'CCC->CCA', 'CCC->CCT', 'CCC->CCG', 'CCA->ACA', 'CCA->TCA', 'CCA->GCA', 'CCA->CAA', 'CCA->CTA', 'CCA->CGA', 'CCA->CCT', 'CCA->CCG', 'CCA->CCC', 'CCG->ACG', 'CCG->TCG', 'CCG->GCG', 'CCG->CAG', 'CCG->CTG',
    'CCG->CGG', 'CCG->CCA', 'CCG->CCT', 'CCG->CCC', 'CAT->AAT', 'CAT->TAT', 'CAT->GAT', 'CAT->CTT', 'CAT->CGT', 'CAT->CCT', 'CAT->CAA', 'CAT->CAG', 'CAT->CAC', 'CAC->AAC', 'CAC->TAC', 'CAC->GAC', 'CAC->CTC', 'CAC->CGC', 'CAC->CCC',
    'CAC->CAA', 'CAC->CAT', 'CAC->CAG', 'CAA->AAA', 'CAA->GAA', 'CAA->CTA', 'CAA->CGA', 'CAA->CCA', 'CAA->CAT', 'CAA->CAG', 'CAA->CAC', 'CAG->AAG', 'CAG->GAG', 'CAG->CTG', 'CAG->CGG', 'CAG->CCG', 'CAG->CAA', 'CAG->CAT', 'CAG->CAC',
    'CGT->AGT', 'CGT->TGT', 'CGT->GGT', 'CGT->CAT', 'CGT->CTT', 'CGT->CCT', 'CGT->CGA', 'CGT->CGG', 'CGT->CGC', 'CGC->AGC', 'CGC->TGC', 'CGC->GGC', 'CGC->CAC', 'CGC->CTC', 'CGC->CCC', 'CGC->CGA', 'CGC->CGT', 'CGC->CGG', 'CGA->AGA',
    'CGA->GGA', 'CGA->CAA', 'CGA->CTA', 'CGA->CCA', 'CGA->CGT', 'CGA->CGG', 'CGA->CGC', 'CGG->AGG', 'CGG->TGG', 'CGG->GGG', 'CGG->CAG', 'CGG->CTG', 'CGG->CCG', 'CGG->CGA', 'CGG->CGT', 'CGG->CGC', 'ATT->TTT', 'ATT->GTT', 'ATT->CTT',
    'ATT->AAT', 'ATT->AGT', 'ATT->ACT', 'ATT->ATA', 'ATT->ATG', 'ATT->ATC', 'ATC->TTC', 'ATC->GTC', 'ATC->CTC', 'ATC->AAC', 'ATC->AGC', 'ATC->ACC', 'ATC->ATA', 'ATC->ATT', 'ATC->ATG', 'ATA->TTA', 'ATA->GTA', 'ATA->CTA', 'ATA->AAA',
    'ATA->AGA', 'ATA->ACA', 'ATA->ATT', 'ATA->ATG', 'ATA->ATC', 'ATG->TTG', 'ATG->GTG', 'ATG->CTG', 'ATG->AAG', 'ATG->AGG', 'ATG->ACG', 'ATG->ATA', 'ATG->ATT', 'ATG->ATC', 'ACT->TCT', 'ACT->GCT', 'ACT->CCT', 'ACT->AAT', 'ACT->ATT',
    'ACT->AGT', 'ACT->ACA', 'ACT->ACG', 'ACT->ACC', 'ACC->TCC', 'ACC->GCC', 'ACC->CCC', 'ACC->AAC', 'ACC->ATC', 'ACC->AGC', 'ACC->ACA', 'ACC->ACT', 'ACC->ACG', 'ACA->TCA', 'ACA->GCA', 'ACA->CCA', 'ACA->AAA', 'ACA->ATA', 'ACA->AGA',
    'ACA->ACT', 'ACA->ACG', 'ACA->ACC', 'ACG->TCG', 'ACG->GCG', 'ACG->CCG', 'ACG->AAG', 'ACG->ATG', 'ACG->AGG', 'ACG->ACA', 'ACG->ACT', 'ACG->ACC', 'AAT->TAT', 'AAT->GAT', 'AAT->CAT', 'AAT->ATT', 'AAT->AGT', 'AAT->ACT', 'AAT->AAA',
    'AAT->AAG', 'AAT->AAC', 'AAC->TAC', 'AAC->GAC', 'AAC->CAC', 'AAC->ATC', 'AAC->AGC', 'AAC->ACC', 'AAC->AAA', 'AAC->AAT', 'AAC->AAG', 'AAA->GAA', 'AAA->CAA', 'AAA->ATA', 'AAA->AGA', 'AAA->ACA', 'AAA->AAT', 'AAA->AAG', 'AAA->AAC',
    'AAG->GAG', 'AAG->CAG', 'AAG->ATG', 'AAG->AGG', 'AAG->ACG', 'AAG->AAA', 'AAG->AAT', 'AAG->AAC', 'AGT->TGT', 'AGT->GGT', 'AGT->CGT', 'AGT->AAT', 'AGT->ATT', 'AGT->ACT', 'AGT->AGA', 'AGT->AGG', 'AGT->AGC', 'AGC->TGC', 'AGC->GGC',
    'AGC->CGC', 'AGC->AAC', 'AGC->ATC', 'AGC->ACC', 'AGC->AGA', 'AGC->AGT', 'AGC->AGG', 'AGA->GGA', 'AGA->CGA', 'AGA->AAA', 'AGA->ATA', 'AGA->ACA', 'AGA->AGT', 'AGA->AGG', 'AGA->AGC', 'AGG->TGG', 'AGG->GGG', 'AGG->CGG', 'AGG->AAG',
    'AGG->ATG', 'AGG->ACG', 'AGG->AGA', 'AGG->AGT', 'AGG->AGC', 'GTT->ATT', 'GTT->TTT', 'GTT->CTT', 'GTT->GAT', 'GTT->GGT', 'GTT->GCT', 'GTT->GTA', 'GTT->GTG', 'GTT->GTC', 'GTC->ATC', 'GTC->TTC', 'GTC->CTC', 'GTC->GAC', 'GTC->GGC',
    'GTC->GCC', 'GTC->GTA', 'GTC->GTT', 'GTC->GTG', 'GTA->ATA', 'GTA->TTA', 'GTA->CTA', 'GTA->GAA', 'GTA->GGA', 'GTA->GCA', 'GTA->GTT', 'GTA->GTG', 'GTA->GTC', 'GTG->ATG', 'GTG->TTG', 'GTG->CTG', 'GTG->GAG', 'GTG->GGG', 'GTG->GCG',
    'GTG->GTA', 'GTG->GTT', 'GTG->GTC', 'GCT->ACT', 'GCT->TCT', 'GCT->CCT', 'GCT->GAT', 'GCT->GTT', 'GCT->GGT', 'GCT->GCA', 'GCT->GCG', 'GCT->GCC', 'GCC->ACC', 'GCC->TCC', 'GCC->CCC', 'GCC->GAC', 'GCC->GTC', 'GCC->GGC', 'GCC->GCA',
    'GCC->GCT', 'GCC->GCG', 'GCA->ACA', 'GCA->TCA', 'GCA->CCA', 'GCA->GAA', 'GCA->GTA', 'GCA->GGA', 'GCA->GCT', 'GCA->GCG', 'GCA->GCC', 'GCG->ACG', 'GCG->TCG', 'GCG->CCG', 'GCG->GAG', 'GCG->GTG', 'GCG->GGG', 'GCG->GCA', 'GCG->GCT',
    'GCG->GCC', 'GAT->AAT', 'GAT->TAT', 'GAT->CAT', 'GAT->GTT', 'GAT->GGT', 'GAT->GCT', 'GAT->GAA', 'GAT->GAG', 'GAT->GAC', 'GAC->AAC', 'GAC->TAC', 'GAC->CAC', 'GAC->GTC', 'GAC->GGC', 'GAC->GCC', 'GAC->GAA', 'GAC->GAT', 'GAC->GAG',
    'GAA->AAA', 'GAA->CAA', 'GAA->GTA', 'GAA->GGA', 'GAA->GCA', 'GAA->GAT', 'GAA->GAG', 'GAA->GAC', 'GAG->AAG', 'GAG->CAG', 'GAG->GTG', 'GAG->GGG', 'GAG->GCG', 'GAG->GAA', 'GAG->GAT', 'GAG->GAC', 'GGT->AGT', 'GGT->TGT', 'GGT->CGT',
    'GGT->GAT', 'GGT->GTT', 'GGT->GCT', 'GGT->GGA', 'GGT->GGG', 'GGT->GGC', 'GGC->AGC', 'GGC->TGC', 'GGC->CGC', 'GGC->GAC', 'GGC->GTC', 'GGC->GCC', 'GGC->GGA', 'GGC->GGT', 'GGC->GGG', 'GGA->AGA', 'GGA->CGA', 'GGA->GAA', 'GGA->GTA',
    'GGA->GCA', 'GGA->GGT', 'GGA->GGG', 'GGA->GGC', 'GGG->GTG', 'GGG->AGG', 'GGG->CGG', 'GGG->GGA', 'GGG->GGC', 'GGG->TGG', 'GGG->GCG', 'GGG->GGT', 'GGG->GAG',
    ]

no_stop_codon_2_internal_mutations_table_list = [
    'TTT->AAT', 'TTT->AGT', 'TTT->ACT', 'TTT->GAT', 'TTT->GGT', 'TTT->GCT', 'TTT->CAT', 'TTT->CGT', 'TTT->CCT', 'TTT->TAC',
    'TTT->TGG', 'TTT->TGC', 'TTT->TCA', 'TTT->TCG', 'TTT->TCC', 'TTT->ATA', 'TTT->ATG', 'TTT->ATC', 'TTT->GTA', 'TTT->GTG',
    'TTT->GTC', 'TTT->CTA', 'TTT->CTG', 'TTT->CTC', 'TTC->AAC', 'TTC->AGC', 'TTC->ACC', 'TTC->GAC', 'TTC->GGC', 'TTC->GCC',
    'TTC->CAC', 'TTC->CGC', 'TTC->CCC', 'TTC->TAT', 'TTC->TGT', 'TTC->TGG', 'TTC->TCA', 'TTC->TCT', 'TTC->TCG', 'TTC->ATA',
    'TTC->ATT', 'TTC->ATG', 'TTC->GTA', 'TTC->GTT', 'TTC->GTG', 'TTC->CTA', 'TTC->CTT', 'TTC->CTG', 'TTA->AAA', 'TTA->AGA',
    'TTA->ACA', 'TTA->GAA', 'TTA->GGA', 'TTA->GCA', 'TTA->CAA', 'TTA->CGA', 'TTA->CCA', 'TTA->TAT', 'TTA->TAC', 'TTA->TGT',
    'TTA->TGG', 'TTA->TGC', 'TTA->TCT', 'TTA->TCG', 'TTA->TCC', 'TTA->ATT', 'TTA->ATG', 'TTA->ATC', 'TTA->GTT', 'TTA->GTG',
    'TTA->GTC', 'TTA->CTT', 'TTA->CTG', 'TTA->CTC', 'TTG->AAG', 'TTG->AGG', 'TTG->ACG', 'TTG->GAG', 'TTG->GGG', 'TTG->GCG',
    'TTG->CAG', 'TTG->CGG', 'TTG->CCG', 'TTG->TAT', 'TTG->TAC', 'TTG->TGT', 'TTG->TGC', 'TTG->TCA', 'TTG->TCT', 'TTG->TCC',
    'TTG->ATA', 'TTG->ATT', 'TTG->ATC', 'TTG->GTA', 'TTG->GTT', 'TTG->GTC', 'TTG->CTA', 'TTG->CTT', 'TTG->CTC', 'TCT->AAT',
    'TCT->ATT', 'TCT->AGT', 'TCT->GAT', 'TCT->GTT', 'TCT->GGT', 'TCT->CAT', 'TCT->CTT', 'TCT->CGT', 'TCT->TAC', 'TCT->TTA',
    'TCT->TTG', 'TCT->TTC', 'TCT->TGG', 'TCT->TGC', 'TCT->ACA', 'TCT->ACG', 'TCT->ACC', 'TCT->GCA', 'TCT->GCG', 'TCT->GCC',
    'TCT->CCA', 'TCT->CCG', 'TCT->CCC', 'TCC->AAC', 'TCC->ATC', 'TCC->AGC', 'TCC->GAC', 'TCC->GTC', 'TCC->GGC', 'TCC->CAC',
    'TCC->CTC', 'TCC->CGC', 'TCC->TAT', 'TCC->TTA', 'TCC->TTT', 'TCC->TTG', 'TCC->TGT', 'TCC->TGG', 'TCC->ACA', 'TCC->ACT',
    'TCC->ACG', 'TCC->GCA', 'TCC->GCT', 'TCC->GCG', 'TCC->CCA', 'TCC->CCT', 'TCC->CCG', 'TCA->AAA', 'TCA->ATA', 'TCA->AGA',
    'TCA->GAA', 'TCA->GTA', 'TCA->GGA', 'TCA->CAA', 'TCA->CTA', 'TCA->CGA', 'TCA->TAT', 'TCA->TAC', 'TCA->TTT', 'TCA->TTG',
    'TCA->TTC', 'TCA->TGT', 'TCA->TGG', 'TCA->TGC', 'TCA->ACT', 'TCA->ACG', 'TCA->ACC', 'TCA->GCT', 'TCA->GCG', 'TCA->GCC',
    'TCA->CCT', 'TCA->CCG', 'TCA->CCC', 'TCG->AAG', 'TCG->ATG', 'TCG->AGG', 'TCG->GAG', 'TCG->GTG', 'TCG->GGG', 'TCG->CAG',
    'TCG->CTG', 'TCG->CGG', 'TCG->TAT', 'TCG->TAC', 'TCG->TTA', 'TCG->TTT', 'TCG->TTC', 'TCG->TGT', 'TCG->TGC', 'TCG->ACA',
    'TCG->ACT', 'TCG->ACC', 'TCG->GCA', 'TCG->GCT', 'TCG->GCC', 'TCG->CCA', 'TCG->CCT', 'TCG->CCC', 'TAT->ATT', 'TAT->AGT',
    'TAT->ACT', 'TAT->GTT', 'TAT->GGT', 'TAT->GCT', 'TAT->CTT', 'TAT->CGT', 'TAT->CCT', 'TAT->TTA', 'TAT->TTG', 'TAT->TTC',
    'TAT->TGG', 'TAT->TGC', 'TAT->TCA', 'TAT->TCG', 'TAT->TCC', 'TAT->AAA', 'TAT->AAG', 'TAT->AAC', 'TAT->GAA', 'TAT->GAG',
    'TAT->GAC', 'TAT->CAA', 'TAT->CAG', 'TAT->CAC', 'TAC->ATC', 'TAC->AGC', 'TAC->ACC', 'TAC->GTC', 'TAC->GGC', 'TAC->GCC',
    'TAC->CTC', 'TAC->CGC', 'TAC->CCC', 'TAC->TTA', 'TAC->TTT', 'TAC->TTG', 'TAC->TGT', 'TAC->TGG', 'TAC->TCA', 'TAC->TCT',
    'TAC->TCG', 'TAC->AAA', 'TAC->AAT', 'TAC->AAG', 'TAC->GAA', 'TAC->GAT', 'TAC->GAG', 'TAC->CAA', 'TAC->CAT', 'TAC->CAG',
    'TGT->AAT', 'TGT->ATT', 'TGT->ACT', 'TGT->GAT', 'TGT->GTT', 'TGT->GCT', 'TGT->CAT', 'TGT->CTT', 'TGT->CCT', 'TGT->TAC',
    'TGT->TTA', 'TGT->TTG', 'TGT->TTC', 'TGT->TCA', 'TGT->TCG', 'TGT->TCC', 'TGT->AGA', 'TGT->AGG', 'TGT->AGC', 'TGT->GGA',
    'TGT->GGG', 'TGT->GGC', 'TGT->CGA', 'TGT->CGG', 'TGT->CGC', 'TGC->AAC', 'TGC->ATC', 'TGC->ACC', 'TGC->GAC', 'TGC->GTC',
    'TGC->GCC', 'TGC->CAC', 'TGC->CTC', 'TGC->CCC', 'TGC->TAT', 'TGC->TTA', 'TGC->TTT', 'TGC->TTG', 'TGC->TCA', 'TGC->TCT',
    'TGC->TCG', 'TGC->AGA', 'TGC->AGT', 'TGC->AGG', 'TGC->GGA', 'TGC->GGT', 'TGC->GGG', 'TGC->CGA', 'TGC->CGT', 'TGC->CGG',
    'TGG->AAG', 'TGG->ATG', 'TGG->ACG', 'TGG->GAG', 'TGG->GTG', 'TGG->GCG', 'TGG->CAG', 'TGG->CTG', 'TGG->CCG', 'TGG->TAT',
    'TGG->TAC', 'TGG->TTA', 'TGG->TTT', 'TGG->TTC', 'TGG->TCA', 'TGG->TCT', 'TGG->TCC', 'TGG->AGA', 'TGG->AGT', 'TGG->AGC',
    'TGG->GGA', 'TGG->GGT', 'TGG->GGC', 'TGG->CGA', 'TGG->CGT', 'TGG->CGC', 'CTT->AAT', 'CTT->AGT', 'CTT->ACT', 'CTT->TAT',
    'CTT->TGT', 'CTT->TCT', 'CTT->GAT', 'CTT->GGT', 'CTT->GCT', 'CTT->CAA', 'CTT->CAG', 'CTT->CAC', 'CTT->CGA', 'CTT->CGG',
    'CTT->CGC', 'CTT->CCA', 'CTT->CCG', 'CTT->CCC', 'CTT->ATA', 'CTT->ATG', 'CTT->ATC', 'CTT->TTA', 'CTT->TTG', 'CTT->TTC',
    'CTT->GTA', 'CTT->GTG', 'CTT->GTC', 'CTC->AAC', 'CTC->AGC', 'CTC->ACC', 'CTC->TAC', 'CTC->TGC', 'CTC->TCC', 'CTC->GAC',
    'CTC->GGC', 'CTC->GCC', 'CTC->CAA', 'CTC->CAT', 'CTC->CAG', 'CTC->CGA', 'CTC->CGT', 'CTC->CGG', 'CTC->CCA', 'CTC->CCT',
    'CTC->CCG', 'CTC->ATA', 'CTC->ATT', 'CTC->ATG', 'CTC->TTA', 'CTC->TTT', 'CTC->TTG', 'CTC->GTA', 'CTC->GTT', 'CTC->GTG',
    'CTA->AAA', 'CTA->AGA', 'CTA->ACA', 'CTA->TCA', 'CTA->GAA', 'CTA->GGA', 'CTA->GCA', 'CTA->CAT', 'CTA->CAG', 'CTA->CAC',
    'CTA->CGT', 'CTA->CGG', 'CTA->CGC', 'CTA->CCT', 'CTA->CCG', 'CTA->CCC', 'CTA->ATT', 'CTA->ATG', 'CTA->ATC', 'CTA->TTT',
    'CTA->TTG', 'CTA->TTC', 'CTA->GTT', 'CTA->GTG', 'CTA->GTC', 'CTG->AAG', 'CTG->AGG', 'CTG->ACG', 'CTG->TGG', 'CTG->TCG',
    'CTG->GAG', 'CTG->GGG', 'CTG->GCG', 'CTG->CAA', 'CTG->CAT', 'CTG->CAC', 'CTG->CGA', 'CTG->CGT', 'CTG->CGC', 'CTG->CCA',
    'CTG->CCT', 'CTG->CCC', 'CTG->ATA', 'CTG->ATT', 'CTG->ATC', 'CTG->TTA', 'CTG->TTT', 'CTG->TTC', 'CTG->GTA', 'CTG->GTT',
    'CTG->GTC', 'CCT->AAT', 'CCT->ATT', 'CCT->AGT', 'CCT->TAT', 'CCT->TTT', 'CCT->TGT', 'CCT->GAT', 'CCT->GTT', 'CCT->GGT',
    'CCT->CAA', 'CCT->CAG', 'CCT->CAC', 'CCT->CTA', 'CCT->CTG', 'CCT->CTC', 'CCT->CGA', 'CCT->CGG', 'CCT->CGC', 'CCT->ACA',
    'CCT->ACG', 'CCT->ACC', 'CCT->TCA', 'CCT->TCG', 'CCT->TCC', 'CCT->GCA', 'CCT->GCG', 'CCT->GCC', 'CCC->AAC', 'CCC->ATC',
    'CCC->AGC', 'CCC->TAC', 'CCC->TTC', 'CCC->TGC', 'CCC->GAC', 'CCC->GTC', 'CCC->GGC', 'CCC->CAA', 'CCC->CAT', 'CCC->CAG',
    'CCC->CTA', 'CCC->CTT', 'CCC->CTG', 'CCC->CGA', 'CCC->CGT', 'CCC->CGG', 'CCC->ACA', 'CCC->ACT', 'CCC->ACG', 'CCC->TCA',
    'CCC->TCT', 'CCC->TCG', 'CCC->GCA', 'CCC->GCT', 'CCC->GCG', 'CCA->AAA', 'CCA->ATA', 'CCA->AGA', 'CCA->TTA', 'CCA->GAA',
    'CCA->GTA', 'CCA->GGA', 'CCA->CAT', 'CCA->CAG', 'CCA->CAC', 'CCA->CTT', 'CCA->CTG', 'CCA->CTC', 'CCA->CGT', 'CCA->CGG',
    'CCA->CGC', 'CCA->ACT', 'CCA->ACG', 'CCA->ACC', 'CCA->TCT', 'CCA->TCG', 'CCA->TCC', 'CCA->GCT', 'CCA->GCG', 'CCA->GCC',
    'CCG->AAG', 'CCG->ATG', 'CCG->AGG', 'CCG->TTG', 'CCG->TGG', 'CCG->GAG', 'CCG->GTG', 'CCG->GGG', 'CCG->CAA', 'CCG->CAT',
    'CCG->CAC', 'CCG->CTA', 'CCG->CTT', 'CCG->CTC', 'CCG->CGA', 'CCG->CGT', 'CCG->CGC', 'CCG->ACA', 'CCG->ACT', 'CCG->ACC',
    'CCG->TCA', 'CCG->TCT', 'CCG->TCC', 'CCG->GCA', 'CCG->GCT', 'CCG->GCC', 'CAT->ATT', 'CAT->AGT', 'CAT->ACT', 'CAT->TTT',
    'CAT->TGT', 'CAT->TCT', 'CAT->GTT', 'CAT->GGT', 'CAT->GCT', 'CAT->CTA', 'CAT->CTG', 'CAT->CTC', 'CAT->CGA', 'CAT->CGG',
    'CAT->CGC', 'CAT->CCA', 'CAT->CCG', 'CAT->CCC', 'CAT->AAA', 'CAT->AAG', 'CAT->AAC', 'CAT->TAC', 'CAT->GAA', 'CAT->GAG',
    'CAT->GAC', 'CAC->ATC', 'CAC->AGC', 'CAC->ACC', 'CAC->TTC', 'CAC->TGC', 'CAC->TCC', 'CAC->GTC', 'CAC->GGC', 'CAC->GCC',
    'CAC->CTA', 'CAC->CTT', 'CAC->CTG', 'CAC->CGA', 'CAC->CGT', 'CAC->CGG', 'CAC->CCA', 'CAC->CCT', 'CAC->CCG', 'CAC->AAA',
    'CAC->AAT', 'CAC->AAG', 'CAC->TAT', 'CAC->GAA', 'CAC->GAT', 'CAC->GAG', 'CAA->ATA', 'CAA->AGA', 'CAA->ACA', 'CAA->TTA',
    'CAA->TCA', 'CAA->GTA', 'CAA->GGA', 'CAA->GCA', 'CAA->CTT', 'CAA->CTG', 'CAA->CTC', 'CAA->CGT', 'CAA->CGG', 'CAA->CGC',
    'CAA->CCT', 'CAA->CCG', 'CAA->CCC', 'CAA->AAT', 'CAA->AAG', 'CAA->AAC', 'CAA->TAT', 'CAA->TAC', 'CAA->GAT', 'CAA->GAG',
    'CAA->GAC', 'CAG->ATG', 'CAG->AGG', 'CAG->ACG', 'CAG->TTG', 'CAG->TGG', 'CAG->TCG', 'CAG->GTG', 'CAG->GGG', 'CAG->GCG',
    'CAG->CTA', 'CAG->CTT', 'CAG->CTC', 'CAG->CGA', 'CAG->CGT', 'CAG->CGC', 'CAG->CCA', 'CAG->CCT', 'CAG->CCC', 'CAG->AAA',
    'CAG->AAT', 'CAG->AAC', 'CAG->TAT', 'CAG->TAC', 'CAG->GAA', 'CAG->GAT', 'CAG->GAC', 'CGT->AAT', 'CGT->ATT', 'CGT->ACT',
    'CGT->TAT', 'CGT->TTT', 'CGT->TCT', 'CGT->GAT', 'CGT->GTT', 'CGT->GCT', 'CGT->CAA', 'CGT->CAG', 'CGT->CAC', 'CGT->CTA',
    'CGT->CTG', 'CGT->CTC', 'CGT->CCA', 'CGT->CCG', 'CGT->CCC', 'CGT->AGA', 'CGT->AGG', 'CGT->AGC', 'CGT->TGG', 'CGT->TGC',
    'CGT->GGA', 'CGT->GGG', 'CGT->GGC', 'CGC->AAC', 'CGC->ATC', 'CGC->ACC', 'CGC->TAC', 'CGC->TTC', 'CGC->TCC', 'CGC->GAC',
    'CGC->GTC', 'CGC->GCC', 'CGC->CAA', 'CGC->CAT', 'CGC->CAG', 'CGC->CTA', 'CGC->CTT', 'CGC->CTG', 'CGC->CCA', 'CGC->CCT',
    'CGC->CCG', 'CGC->AGA', 'CGC->AGT', 'CGC->AGG', 'CGC->TGT', 'CGC->TGG', 'CGC->GGA', 'CGC->GGT', 'CGC->GGG', 'CGA->AAA',
    'CGA->ATA', 'CGA->ACA', 'CGA->TTA', 'CGA->TCA', 'CGA->GAA', 'CGA->GTA', 'CGA->GCA', 'CGA->CAT', 'CGA->CAG', 'CGA->CAC',
    'CGA->CTT', 'CGA->CTG', 'CGA->CTC', 'CGA->CCT', 'CGA->CCG', 'CGA->CCC', 'CGA->AGT', 'CGA->AGG', 'CGA->AGC', 'CGA->TGT',
    'CGA->TGG', 'CGA->TGC', 'CGA->GGT', 'CGA->GGG', 'CGA->GGC', 'CGG->AAG', 'CGG->ATG', 'CGG->ACG', 'CGG->TTG', 'CGG->TCG',
    'CGG->GAG', 'CGG->GTG', 'CGG->GCG', 'CGG->CAA', 'CGG->CAT', 'CGG->CAC', 'CGG->CTA', 'CGG->CTT', 'CGG->CTC', 'CGG->CCA',
    'CGG->CCT', 'CGG->CCC', 'CGG->AGA', 'CGG->AGT', 'CGG->AGC', 'CGG->TGT', 'CGG->TGC', 'CGG->GGA', 'CGG->GGT', 'CGG->GGC',
    'ATT->TAT', 'ATT->TGT', 'ATT->TCT', 'ATT->GAT', 'ATT->GGT', 'ATT->GCT', 'ATT->CAT', 'ATT->CGT', 'ATT->CCT', 'ATT->AAA',
    'ATT->AAG', 'ATT->AAC', 'ATT->AGA', 'ATT->AGG', 'ATT->AGC', 'ATT->ACA', 'ATT->ACG', 'ATT->ACC', 'ATT->TTA', 'ATT->TTG',
    'ATT->TTC', 'ATT->GTA', 'ATT->GTG', 'ATT->GTC', 'ATT->CTA', 'ATT->CTG', 'ATT->CTC', 'ATC->TAC', 'ATC->TGC', 'ATC->TCC',
    'ATC->GAC', 'ATC->GGC', 'ATC->GCC', 'ATC->CAC', 'ATC->CGC', 'ATC->CCC', 'ATC->AAA', 'ATC->AAT', 'ATC->AAG', 'ATC->AGA',
    'ATC->AGT', 'ATC->AGG', 'ATC->ACA', 'ATC->ACT', 'ATC->ACG', 'ATC->TTA', 'ATC->TTT', 'ATC->TTG', 'ATC->GTA', 'ATC->GTT',
    'ATC->GTG', 'ATC->CTA', 'ATC->CTT', 'ATC->CTG', 'ATA->TCA', 'ATA->GAA', 'ATA->GGA', 'ATA->GCA', 'ATA->CAA', 'ATA->CGA',
    'ATA->CCA', 'ATA->AAT', 'ATA->AAG', 'ATA->AAC', 'ATA->AGT', 'ATA->AGG', 'ATA->AGC', 'ATA->ACT', 'ATA->ACG', 'ATA->ACC',
    'ATA->TTT', 'ATA->TTG', 'ATA->TTC', 'ATA->GTT', 'ATA->GTG', 'ATA->GTC', 'ATA->CTT', 'ATA->CTG', 'ATA->CTC', 'ATG->TGG',
    'ATG->TCG', 'ATG->GAG', 'ATG->GGG', 'ATG->GCG', 'ATG->CAG', 'ATG->CGG', 'ATG->CCG', 'ATG->AAA', 'ATG->AAT', 'ATG->AAC',
    'ATG->AGA', 'ATG->AGT', 'ATG->AGC', 'ATG->ACA', 'ATG->ACT', 'ATG->ACC', 'ATG->TTA', 'ATG->TTT', 'ATG->TTC', 'ATG->GTA',
    'ATG->GTT', 'ATG->GTC', 'ATG->CTA', 'ATG->CTT', 'ATG->CTC', 'ACT->TAT', 'ACT->TTT', 'ACT->TGT', 'ACT->GAT', 'ACT->GTT',
    'ACT->GGT', 'ACT->CAT', 'ACT->CTT', 'ACT->CGT', 'ACT->AAA', 'ACT->AAG', 'ACT->AAC', 'ACT->ATA', 'ACT->ATG', 'ACT->ATC',
    'ACT->AGA', 'ACT->AGG', 'ACT->AGC', 'ACT->TCA', 'ACT->TCG', 'ACT->TCC', 'ACT->GCA', 'ACT->GCG', 'ACT->GCC', 'ACT->CCA',
    'ACT->CCG', 'ACT->CCC', 'ACC->TAC', 'ACC->TTC', 'ACC->TGC', 'ACC->GAC', 'ACC->GTC', 'ACC->GGC', 'ACC->CAC', 'ACC->CTC',
    'ACC->CGC', 'ACC->AAA', 'ACC->AAT', 'ACC->AAG', 'ACC->ATA', 'ACC->ATT', 'ACC->ATG', 'ACC->AGA', 'ACC->AGT', 'ACC->AGG',
    'ACC->TCA', 'ACC->TCT', 'ACC->TCG', 'ACC->GCA', 'ACC->GCT', 'ACC->GCG', 'ACC->CCA', 'ACC->CCT', 'ACC->CCG', 'ACA->TTA',
    'ACA->GAA', 'ACA->GTA', 'ACA->GGA', 'ACA->CAA', 'ACA->CTA', 'ACA->CGA', 'ACA->AAT', 'ACA->AAG', 'ACA->AAC', 'ACA->ATT',
    'ACA->ATG', 'ACA->ATC', 'ACA->AGT', 'ACA->AGG', 'ACA->AGC', 'ACA->TCT', 'ACA->TCG', 'ACA->TCC', 'ACA->GCT', 'ACA->GCG',
    'ACA->GCC', 'ACA->CCT', 'ACA->CCG', 'ACA->CCC', 'ACG->TTG', 'ACG->TGG', 'ACG->GAG', 'ACG->GTG', 'ACG->GGG', 'ACG->CAG',
    'ACG->CTG', 'ACG->CGG', 'ACG->AAA', 'ACG->AAT', 'ACG->AAC', 'ACG->ATA', 'ACG->ATT', 'ACG->ATC', 'ACG->AGA', 'ACG->AGT',
    'ACG->AGC', 'ACG->TCA', 'ACG->TCT', 'ACG->TCC', 'ACG->GCA', 'ACG->GCT', 'ACG->GCC', 'ACG->CCA', 'ACG->CCT', 'ACG->CCC',
    'AAT->TTT', 'AAT->TGT', 'AAT->TCT', 'AAT->GTT', 'AAT->GGT', 'AAT->GCT', 'AAT->CTT', 'AAT->CGT', 'AAT->CCT', 'AAT->ATA',
    'AAT->ATG', 'AAT->ATC', 'AAT->AGA', 'AAT->AGG', 'AAT->AGC', 'AAT->ACA', 'AAT->ACG', 'AAT->ACC', 'AAT->TAC', 'AAT->GAA',
    'AAT->GAG', 'AAT->GAC', 'AAT->CAA', 'AAT->CAG', 'AAT->CAC', 'AAC->TTC', 'AAC->TGC', 'AAC->TCC', 'AAC->GTC', 'AAC->GGC',
    'AAC->GCC', 'AAC->CTC', 'AAC->CGC', 'AAC->CCC', 'AAC->ATA', 'AAC->ATT', 'AAC->ATG', 'AAC->AGA', 'AAC->AGT', 'AAC->AGG',
    'AAC->ACA', 'AAC->ACT', 'AAC->ACG', 'AAC->TAT', 'AAC->GAA', 'AAC->GAT', 'AAC->GAG', 'AAC->CAA', 'AAC->CAT', 'AAC->CAG',
    'AAA->TTA', 'AAA->TCA', 'AAA->GTA', 'AAA->GGA', 'AAA->GCA', 'AAA->CTA', 'AAA->CGA', 'AAA->CCA', 'AAA->ATT', 'AAA->ATG',
    'AAA->ATC', 'AAA->AGT', 'AAA->AGG', 'AAA->AGC', 'AAA->ACT', 'AAA->ACG', 'AAA->ACC', 'AAA->TAT', 'AAA->TAC', 'AAA->GAT',
    'AAA->GAG', 'AAA->GAC', 'AAA->CAT', 'AAA->CAG', 'AAA->CAC', 'AAG->TTG', 'AAG->TGG', 'AAG->TCG', 'AAG->GTG', 'AAG->GGG',
    'AAG->GCG', 'AAG->CTG', 'AAG->CGG', 'AAG->CCG', 'AAG->ATA', 'AAG->ATT', 'AAG->ATC', 'AAG->AGA', 'AAG->AGT', 'AAG->AGC',
    'AAG->ACA', 'AAG->ACT', 'AAG->ACC', 'AAG->TAT', 'AAG->TAC', 'AAG->GAA', 'AAG->GAT', 'AAG->GAC', 'AAG->CAA', 'AAG->CAT',
    'AAG->CAC', 'AGT->TAT', 'AGT->TTT', 'AGT->TCT', 'AGT->GAT', 'AGT->GTT', 'AGT->GCT', 'AGT->CAT', 'AGT->CTT', 'AGT->CCT',
    'AGT->AAA', 'AGT->AAG', 'AGT->AAC', 'AGT->ATA', 'AGT->ATG', 'AGT->ATC', 'AGT->ACA', 'AGT->ACG', 'AGT->ACC', 'AGT->TGG',
    'AGT->TGC', 'AGT->GGA', 'AGT->GGG', 'AGT->GGC', 'AGT->CGA', 'AGT->CGG', 'AGT->CGC', 'AGC->TAC', 'AGC->TTC', 'AGC->TCC',
    'AGC->GAC', 'AGC->GTC', 'AGC->GCC', 'AGC->CAC', 'AGC->CTC', 'AGC->CCC', 'AGC->AAA', 'AGC->AAT', 'AGC->AAG', 'AGC->ATA',
    'AGC->ATT', 'AGC->ATG', 'AGC->ACA', 'AGC->ACT', 'AGC->ACG', 'AGC->TGT', 'AGC->TGG', 'AGC->GGA', 'AGC->GGT', 'AGC->GGG',
    'AGC->CGA', 'AGC->CGT', 'AGC->CGG', 'AGA->TTA', 'AGA->TCA', 'AGA->GAA', 'AGA->GTA', 'AGA->GCA', 'AGA->CAA', 'AGA->CTA',
    'AGA->CCA', 'AGA->AAT', 'AGA->AAG', 'AGA->AAC', 'AGA->ATT', 'AGA->ATG', 'AGA->ATC', 'AGA->ACT', 'AGA->ACG', 'AGA->ACC',
    'AGA->TGT', 'AGA->TGG', 'AGA->TGC', 'AGA->GGT', 'AGA->GGG', 'AGA->GGC', 'AGA->CGT', 'AGA->CGG', 'AGA->CGC', 'AGG->TTG',
    'AGG->TCG', 'AGG->GAG', 'AGG->GTG', 'AGG->GCG', 'AGG->CAG', 'AGG->CTG', 'AGG->CCG', 'AGG->AAA', 'AGG->AAT', 'AGG->AAC',
    'AGG->ATA', 'AGG->ATT', 'AGG->ATC', 'AGG->ACA', 'AGG->ACT', 'AGG->ACC', 'AGG->TGT', 'AGG->TGC', 'AGG->GGA', 'AGG->GGT',
    'AGG->GGC', 'AGG->CGA', 'AGG->CGT', 'AGG->CGC', 'GTT->AAT', 'GTT->AGT', 'GTT->ACT', 'GTT->TAT', 'GTT->TGT', 'GTT->TCT',
    'GTT->CAT', 'GTT->CGT', 'GTT->CCT', 'GTT->GAA', 'GTT->GAG', 'GTT->GAC', 'GTT->GGA', 'GTT->GGG', 'GTT->GGC', 'GTT->GCA',
    'GTT->GCG', 'GTT->GCC', 'GTT->ATA', 'GTT->ATG', 'GTT->ATC', 'GTT->TTA', 'GTT->TTG', 'GTT->TTC', 'GTT->CTA', 'GTT->CTG',
    'GTT->CTC', 'GTC->AAC', 'GTC->AGC', 'GTC->ACC', 'GTC->TAC', 'GTC->TGC', 'GTC->TCC', 'GTC->CAC', 'GTC->CGC', 'GTC->CCC',
    'GTC->GAA', 'GTC->GAT', 'GTC->GAG', 'GTC->GGA', 'GTC->GGT', 'GTC->GGG', 'GTC->GCA', 'GTC->GCT', 'GTC->GCG', 'GTC->ATA',
    'GTC->ATT', 'GTC->ATG', 'GTC->TTA', 'GTC->TTT', 'GTC->TTG', 'GTC->CTA', 'GTC->CTT', 'GTC->CTG', 'GTA->AAA', 'GTA->AGA',
    'GTA->ACA', 'GTA->TCA', 'GTA->CAA', 'GTA->CGA', 'GTA->CCA', 'GTA->GAT', 'GTA->GAG', 'GTA->GAC', 'GTA->GGT', 'GTA->GGG',
    'GTA->GGC', 'GTA->GCT', 'GTA->GCG', 'GTA->GCC', 'GTA->ATT', 'GTA->ATG', 'GTA->ATC', 'GTA->TTT', 'GTA->TTG', 'GTA->TTC',
    'GTA->CTT', 'GTA->CTG', 'GTA->CTC', 'GTG->AAG', 'GTG->AGG', 'GTG->ACG', 'GTG->TGG', 'GTG->TCG', 'GTG->CAG', 'GTG->CGG',
    'GTG->CCG', 'GTG->GAA', 'GTG->GAT', 'GTG->GAC', 'GTG->GGA', 'GTG->GGT', 'GTG->GGC', 'GTG->GCA', 'GTG->GCT', 'GTG->GCC',
    'GTG->ATA', 'GTG->ATT', 'GTG->ATC', 'GTG->TTA', 'GTG->TTT', 'GTG->TTC', 'GTG->CTA', 'GTG->CTT', 'GTG->CTC', 'GCT->AAT',
    'GCT->ATT', 'GCT->AGT', 'GCT->TAT', 'GCT->TTT', 'GCT->TGT', 'GCT->CAT', 'GCT->CTT', 'GCT->CGT', 'GCT->GAA', 'GCT->GAG',
    'GCT->GAC', 'GCT->GTA', 'GCT->GTG', 'GCT->GTC', 'GCT->GGA', 'GCT->GGG', 'GCT->GGC', 'GCT->ACA', 'GCT->ACG', 'GCT->ACC',
    'GCT->TCA', 'GCT->TCG', 'GCT->TCC', 'GCT->CCA', 'GCT->CCG', 'GCT->CCC', 'GCC->AAC', 'GCC->ATC', 'GCC->AGC', 'GCC->TAC',
    'GCC->TTC', 'GCC->TGC', 'GCC->CAC', 'GCC->CTC', 'GCC->CGC', 'GCC->GAA', 'GCC->GAT', 'GCC->GAG', 'GCC->GTA', 'GCC->GTT',
    'GCC->GTG', 'GCC->GGA', 'GCC->GGT', 'GCC->GGG', 'GCC->ACA', 'GCC->ACT', 'GCC->ACG', 'GCC->TCA', 'GCC->TCT', 'GCC->TCG',
    'GCC->CCA', 'GCC->CCT', 'GCC->CCG', 'GCA->AAA', 'GCA->ATA', 'GCA->AGA', 'GCA->TTA', 'GCA->CAA', 'GCA->CTA', 'GCA->CGA',
    'GCA->GAT', 'GCA->GAG', 'GCA->GAC', 'GCA->GTT', 'GCA->GTG', 'GCA->GTC', 'GCA->GGT', 'GCA->GGG', 'GCA->GGC', 'GCA->ACT',
    'GCA->ACG', 'GCA->ACC', 'GCA->TCT', 'GCA->TCG', 'GCA->TCC', 'GCA->CCT', 'GCA->CCG', 'GCA->CCC', 'GCG->AAG', 'GCG->ATG',
    'GCG->AGG', 'GCG->TTG', 'GCG->TGG', 'GCG->CAG', 'GCG->CTG', 'GCG->CGG', 'GCG->GAA', 'GCG->GAT', 'GCG->GAC', 'GCG->GTA',
    'GCG->GTT', 'GCG->GTC', 'GCG->GGA', 'GCG->GGT', 'GCG->GGC', 'GCG->ACA', 'GCG->ACT', 'GCG->ACC', 'GCG->TCA', 'GCG->TCT',
    'GCG->TCC', 'GCG->CCA', 'GCG->CCT', 'GCG->CCC', 'GAT->ATT', 'GAT->AGT', 'GAT->ACT', 'GAT->TTT', 'GAT->TGT', 'GAT->TCT',
    'GAT->CTT', 'GAT->CGT', 'GAT->CCT', 'GAT->GTA', 'GAT->GTG', 'GAT->GTC', 'GAT->GGA', 'GAT->GGG', 'GAT->GGC', 'GAT->GCA',
    'GAT->GCG', 'GAT->GCC', 'GAT->AAA', 'GAT->AAG', 'GAT->AAC', 'GAT->TAC', 'GAT->CAA', 'GAT->CAG', 'GAT->CAC', 'GAC->ATC',
    'GAC->AGC', 'GAC->ACC', 'GAC->TTC', 'GAC->TGC', 'GAC->TCC', 'GAC->CTC', 'GAC->CGC', 'GAC->CCC', 'GAC->GTA', 'GAC->GTT',
    'GAC->GTG', 'GAC->GGA', 'GAC->GGT', 'GAC->GGG', 'GAC->GCA', 'GAC->GCT', 'GAC->GCG', 'GAC->AAA', 'GAC->AAT', 'GAC->AAG',
    'GAC->TAT', 'GAC->CAA', 'GAC->CAT', 'GAC->CAG', 'GAA->ATA', 'GAA->AGA', 'GAA->ACA', 'GAA->TTA', 'GAA->TCA', 'GAA->CTA',
    'GAA->CGA', 'GAA->CCA', 'GAA->GTT', 'GAA->GTG', 'GAA->GTC', 'GAA->GGT', 'GAA->GGG', 'GAA->GGC', 'GAA->GCT', 'GAA->GCG',
    'GAA->GCC', 'GAA->AAT', 'GAA->AAG', 'GAA->AAC', 'GAA->TAT', 'GAA->TAC', 'GAA->CAT', 'GAA->CAG', 'GAA->CAC', 'GAG->ATG',
    'GAG->AGG', 'GAG->ACG', 'GAG->TTG', 'GAG->TGG', 'GAG->TCG', 'GAG->CTG', 'GAG->CGG', 'GAG->CCG', 'GAG->GTA', 'GAG->GTT',
    'GAG->GTC', 'GAG->GGA', 'GAG->GGT', 'GAG->GGC', 'GAG->GCA', 'GAG->GCT', 'GAG->GCC', 'GAG->AAA', 'GAG->AAT', 'GAG->AAC',
    'GAG->TAT', 'GAG->TAC', 'GAG->CAA', 'GAG->CAT', 'GAG->CAC', 'GGT->AAT', 'GGT->ATT', 'GGT->ACT', 'GGT->TAT', 'GGT->TTT',
    'GGT->TCT', 'GGT->CAT', 'GGT->CTT', 'GGT->CCT', 'GGT->GAA', 'GGT->GAG', 'GGT->GAC', 'GGT->GTA', 'GGT->GTG', 'GGT->GTC',
    'GGT->GCA', 'GGT->GCG', 'GGT->GCC', 'GGT->AGA', 'GGT->AGG', 'GGT->AGC', 'GGT->TGG', 'GGT->TGC', 'GGT->CGA', 'GGT->CGG',
    'GGT->CGC', 'GGC->AAC', 'GGC->ATC', 'GGC->ACC', 'GGC->TAC', 'GGC->TTC', 'GGC->TCC', 'GGC->CAC', 'GGC->CTC', 'GGC->CCC',
    'GGC->GAA', 'GGC->GAT', 'GGC->GAG', 'GGC->GTA', 'GGC->GTT', 'GGC->GTG', 'GGC->GCA', 'GGC->GCT', 'GGC->GCG', 'GGC->AGA',
    'GGC->AGT', 'GGC->AGG', 'GGC->TGT', 'GGC->TGG', 'GGC->CGA', 'GGC->CGT', 'GGC->CGG', 'GGA->AAA', 'GGA->ATA', 'GGA->ACA',
    'GGA->TTA', 'GGA->TCA', 'GGA->CAA', 'GGA->CTA', 'GGA->CCA', 'GGA->GAT', 'GGA->GAG', 'GGA->GAC', 'GGA->GTT', 'GGA->GTG',
    'GGA->GTC', 'GGA->GCT', 'GGA->GCG', 'GGA->GCC', 'GGA->AGT', 'GGA->AGG', 'GGA->AGC', 'GGA->TGT', 'GGA->TGG', 'GGA->TGC',
    'GGA->CGT', 'GGA->CGG', 'GGA->CGC', 'GGG->AAG', 'GGG->ATG', 'GGG->ACG', 'GGG->TTG', 'GGG->TCG', 'GGG->CAG', 'GGG->CTG',
    'GGG->CCG', 'GGG->GAA', 'GGG->GAT', 'GGG->GAC', 'GGG->GTA', 'GGG->GTT', 'GGG->GTC', 'GGG->GCA', 'GGG->GCT', 'GGG->GCC',
    'GGG->AGA', 'GGG->AGT', 'GGG->AGC', 'GGG->TGT', 'GGG->TGC', 'GGG->CGA', 'GGG->CGT', 'GGG->CGC'
    ]

no_stop_codon_3_internal_mutations_table_list = [
    'TTT->AAA', 'TTT->AAG', 'TTT->AAC', 'TTT->AGA', 'TTT->AGG', 'TTT->AGC', 'TTT->ACA', 'TTT->ACG', 'TTT->ACC', 'TTT->GAA',
    'TTT->GAG', 'TTT->GAC', 'TTT->GGA', 'TTT->GGG', 'TTT->GGC', 'TTT->GCA', 'TTT->GCG', 'TTT->GCC', 'TTT->CAA', 'TTT->CAG',
    'TTT->CAC', 'TTT->CGA', 'TTT->CGG', 'TTT->CGC', 'TTT->CCA', 'TTT->CCG', 'TTT->CCC', 'TTC->AAA', 'TTC->AAT', 'TTC->AAG',
    'TTC->AGA', 'TTC->AGT', 'TTC->AGG', 'TTC->ACA', 'TTC->ACT', 'TTC->ACG', 'TTC->GAA', 'TTC->GAT', 'TTC->GAG', 'TTC->GGA',
    'TTC->GGT', 'TTC->GGG', 'TTC->GCA', 'TTC->GCT', 'TTC->GCG', 'TTC->CAA', 'TTC->CAT', 'TTC->CAG', 'TTC->CGA', 'TTC->CGT',
    'TTC->CGG', 'TTC->CCA', 'TTC->CCT', 'TTC->CCG', 'TTA->AAT', 'TTA->AAG', 'TTA->AAC', 'TTA->AGT', 'TTA->AGG', 'TTA->AGC',
    'TTA->ACT', 'TTA->ACG', 'TTA->ACC', 'TTA->GAT', 'TTA->GAG', 'TTA->GAC', 'TTA->GGT', 'TTA->GGG', 'TTA->GGC', 'TTA->GCT',
    'TTA->GCG', 'TTA->GCC', 'TTA->CAT', 'TTA->CAG', 'TTA->CAC', 'TTA->CGT', 'TTA->CGG', 'TTA->CGC', 'TTA->CCT', 'TTA->CCG',
    'TTA->CCC', 'TTG->AAA', 'TTG->AAT', 'TTG->AAC', 'TTG->AGA', 'TTG->AGT', 'TTG->AGC', 'TTG->ACA', 'TTG->ACT', 'TTG->ACC',
    'TTG->GAA', 'TTG->GAT', 'TTG->GAC', 'TTG->GGA', 'TTG->GGT', 'TTG->GGC', 'TTG->GCA', 'TTG->GCT', 'TTG->GCC', 'TTG->CAA',
    'TTG->CAT', 'TTG->CAC', 'TTG->CGA', 'TTG->CGT', 'TTG->CGC', 'TTG->CCA', 'TTG->CCT', 'TTG->CCC', 'TCT->AAA', 'TCT->AAG',
    'TCT->AAC', 'TCT->ATA', 'TCT->ATG', 'TCT->ATC', 'TCT->AGA', 'TCT->AGG', 'TCT->AGC', 'TCT->GAA', 'TCT->GAG', 'TCT->GAC',
    'TCT->GTA', 'TCT->GTG', 'TCT->GTC', 'TCT->GGA', 'TCT->GGG', 'TCT->GGC', 'TCT->CAA', 'TCT->CAG', 'TCT->CAC', 'TCT->CTA',
    'TCT->CTG', 'TCT->CTC', 'TCT->CGA', 'TCT->CGG', 'TCT->CGC', 'TCC->AAA', 'TCC->AAT', 'TCC->AAG', 'TCC->ATA', 'TCC->ATT',
    'TCC->ATG', 'TCC->AGA', 'TCC->AGT', 'TCC->AGG', 'TCC->GAA', 'TCC->GAT', 'TCC->GAG', 'TCC->GTA', 'TCC->GTT', 'TCC->GTG',
    'TCC->GGA', 'TCC->GGT', 'TCC->GGG', 'TCC->CAA', 'TCC->CAT', 'TCC->CAG', 'TCC->CTA', 'TCC->CTT', 'TCC->CTG', 'TCC->CGA',
    'TCC->CGT', 'TCC->CGG', 'TCA->AAT', 'TCA->AAG', 'TCA->AAC', 'TCA->ATT', 'TCA->ATG', 'TCA->ATC', 'TCA->AGT', 'TCA->AGG',
    'TCA->AGC', 'TCA->GAT', 'TCA->GAG', 'TCA->GAC', 'TCA->GTT', 'TCA->GTG', 'TCA->GTC', 'TCA->GGT', 'TCA->GGG', 'TCA->GGC',
    'TCA->CAT', 'TCA->CAG', 'TCA->CAC', 'TCA->CTT', 'TCA->CTG', 'TCA->CTC', 'TCA->CGT', 'TCA->CGG', 'TCA->CGC', 'TCG->AAA',
    'TCG->AAT', 'TCG->AAC', 'TCG->ATA', 'TCG->ATT', 'TCG->ATC', 'TCG->AGA', 'TCG->AGT', 'TCG->AGC', 'TCG->GAA', 'TCG->GAT',
    'TCG->GAC', 'TCG->GTA', 'TCG->GTT', 'TCG->GTC', 'TCG->GGA', 'TCG->GGT', 'TCG->GGC', 'TCG->CAA', 'TCG->CAT', 'TCG->CAC',
    'TCG->CTA', 'TCG->CTT', 'TCG->CTC', 'TCG->CGA', 'TCG->CGT', 'TCG->CGC', 'TAT->ATA', 'TAT->ATG', 'TAT->ATC', 'TAT->AGA',
    'TAT->AGG', 'TAT->AGC', 'TAT->ACA', 'TAT->ACG', 'TAT->ACC', 'TAT->GTA', 'TAT->GTG', 'TAT->GTC', 'TAT->GGA', 'TAT->GGG',
    'TAT->GGC', 'TAT->GCA', 'TAT->GCG', 'TAT->GCC', 'TAT->CTA', 'TAT->CTG', 'TAT->CTC', 'TAT->CGA', 'TAT->CGG', 'TAT->CGC',
    'TAT->CCA', 'TAT->CCG', 'TAT->CCC', 'TAC->ATA', 'TAC->ATT', 'TAC->ATG', 'TAC->AGA', 'TAC->AGT', 'TAC->AGG', 'TAC->ACA',
    'TAC->ACT', 'TAC->ACG', 'TAC->GTA', 'TAC->GTT', 'TAC->GTG', 'TAC->GGA', 'TAC->GGT', 'TAC->GGG', 'TAC->GCA', 'TAC->GCT',
    'TAC->GCG', 'TAC->CTA', 'TAC->CTT', 'TAC->CTG', 'TAC->CGA', 'TAC->CGT', 'TAC->CGG', 'TAC->CCA', 'TAC->CCT', 'TAC->CCG',
    'TGT->AAA', 'TGT->AAG', 'TGT->AAC', 'TGT->ATA', 'TGT->ATG', 'TGT->ATC', 'TGT->ACA', 'TGT->ACG', 'TGT->ACC', 'TGT->GAA',
    'TGT->GAG', 'TGT->GAC', 'TGT->GTA', 'TGT->GTG', 'TGT->GTC', 'TGT->GCA', 'TGT->GCG', 'TGT->GCC', 'TGT->CAA', 'TGT->CAG',
    'TGT->CAC', 'TGT->CTA', 'TGT->CTG', 'TGT->CTC', 'TGT->CCA', 'TGT->CCG', 'TGT->CCC', 'TGC->AAA', 'TGC->AAT', 'TGC->AAG',
    'TGC->ATA', 'TGC->ATT', 'TGC->ATG', 'TGC->ACA', 'TGC->ACT', 'TGC->ACG', 'TGC->GAA', 'TGC->GAT', 'TGC->GAG', 'TGC->GTA',
    'TGC->GTT', 'TGC->GTG', 'TGC->GCA', 'TGC->GCT', 'TGC->GCG', 'TGC->CAA', 'TGC->CAT', 'TGC->CAG', 'TGC->CTA', 'TGC->CTT',
    'TGC->CTG', 'TGC->CCA', 'TGC->CCT', 'TGC->CCG', 'TGG->AAA', 'TGG->AAT', 'TGG->AAC', 'TGG->ATA', 'TGG->ATT', 'TGG->ATC',
    'TGG->ACA', 'TGG->ACT', 'TGG->ACC', 'TGG->GAA', 'TGG->GAT', 'TGG->GAC', 'TGG->GTA', 'TGG->GTT', 'TGG->GTC', 'TGG->GCA',
    'TGG->GCT', 'TGG->GCC', 'TGG->CAA', 'TGG->CAT', 'TGG->CAC', 'TGG->CTA', 'TGG->CTT', 'TGG->CTC', 'TGG->CCA', 'TGG->CCT',
    'TGG->CCC', 'CTT->AAA', 'CTT->AAG', 'CTT->AAC', 'CTT->AGA', 'CTT->AGG', 'CTT->AGC', 'CTT->ACA', 'CTT->ACG', 'CTT->ACC',
    'CTT->TAC', 'CTT->TGG', 'CTT->TGC', 'CTT->TCA', 'CTT->TCG', 'CTT->TCC', 'CTT->GAA', 'CTT->GAG', 'CTT->GAC', 'CTT->GGA',
    'CTT->GGG', 'CTT->GGC', 'CTT->GCA', 'CTT->GCG', 'CTT->GCC', 'CTC->AAA', 'CTC->AAT', 'CTC->AAG', 'CTC->AGA', 'CTC->AGT',
    'CTC->AGG', 'CTC->ACA', 'CTC->ACT', 'CTC->ACG', 'CTC->TAT', 'CTC->TGT', 'CTC->TGG', 'CTC->TCA', 'CTC->TCT', 'CTC->TCG',
    'CTC->GAA', 'CTC->GAT', 'CTC->GAG', 'CTC->GGA', 'CTC->GGT', 'CTC->GGG', 'CTC->GCA', 'CTC->GCT', 'CTC->GCG', 'CTA->AAT',
    'CTA->AAG', 'CTA->AAC', 'CTA->AGT', 'CTA->AGG', 'CTA->AGC', 'CTA->ACT', 'CTA->ACG', 'CTA->ACC', 'CTA->TAT', 'CTA->TAC',
    'CTA->TGT', 'CTA->TGG', 'CTA->TGC', 'CTA->TCT', 'CTA->TCG', 'CTA->TCC', 'CTA->GAT', 'CTA->GAG', 'CTA->GAC', 'CTA->GGT',
    'CTA->GGG', 'CTA->GGC', 'CTA->GCT', 'CTA->GCG', 'CTA->GCC', 'CTG->AAA', 'CTG->AAT', 'CTG->AAC', 'CTG->AGA', 'CTG->AGT',
    'CTG->AGC', 'CTG->ACA', 'CTG->ACT', 'CTG->ACC', 'CTG->TAT', 'CTG->TAC', 'CTG->TGT', 'CTG->TGC', 'CTG->TCA', 'CTG->TCT',
    'CTG->TCC', 'CTG->GAA', 'CTG->GAT', 'CTG->GAC', 'CTG->GGA', 'CTG->GGT', 'CTG->GGC', 'CTG->GCA', 'CTG->GCT', 'CTG->GCC',
    'CCT->AAA', 'CCT->AAG', 'CCT->AAC', 'CCT->ATA', 'CCT->ATG', 'CCT->ATC', 'CCT->AGA', 'CCT->AGG', 'CCT->AGC', 'CCT->TAC',
    'CCT->TTA', 'CCT->TTG', 'CCT->TTC', 'CCT->TGG', 'CCT->TGC', 'CCT->GAA', 'CCT->GAG', 'CCT->GAC', 'CCT->GTA', 'CCT->GTG',
    'CCT->GTC', 'CCT->GGA', 'CCT->GGG', 'CCT->GGC', 'CCC->AAA', 'CCC->AAT', 'CCC->AAG', 'CCC->ATA', 'CCC->ATT', 'CCC->ATG',
    'CCC->AGA', 'CCC->AGT', 'CCC->AGG', 'CCC->TAT', 'CCC->TTA', 'CCC->TTT', 'CCC->TTG', 'CCC->TGT', 'CCC->TGG', 'CCC->GAA',
    'CCC->GAT', 'CCC->GAG', 'CCC->GTA', 'CCC->GTT', 'CCC->GTG', 'CCC->GGA', 'CCC->GGT', 'CCC->GGG', 'CCA->AAT', 'CCA->AAG',
    'CCA->AAC', 'CCA->ATT', 'CCA->ATG', 'CCA->ATC', 'CCA->AGT', 'CCA->AGG', 'CCA->AGC', 'CCA->TAT', 'CCA->TAC', 'CCA->TTT',
    'CCA->TTG', 'CCA->TTC', 'CCA->TGT', 'CCA->TGG', 'CCA->TGC', 'CCA->GAT', 'CCA->GAG', 'CCA->GAC', 'CCA->GTT', 'CCA->GTG',
    'CCA->GTC', 'CCA->GGT', 'CCA->GGG', 'CCA->GGC', 'CCG->AAA', 'CCG->AAT', 'CCG->AAC', 'CCG->ATA', 'CCG->ATT', 'CCG->ATC',
    'CCG->AGA', 'CCG->AGT', 'CCG->AGC', 'CCG->TAT', 'CCG->TAC', 'CCG->TTA', 'CCG->TTT', 'CCG->TTC', 'CCG->TGT', 'CCG->TGC',
    'CCG->GAA', 'CCG->GAT', 'CCG->GAC', 'CCG->GTA', 'CCG->GTT', 'CCG->GTC', 'CCG->GGA', 'CCG->GGT', 'CCG->GGC', 'CAT->ATA',
    'CAT->ATG', 'CAT->ATC', 'CAT->AGA', 'CAT->AGG', 'CAT->AGC', 'CAT->ACA', 'CAT->ACG', 'CAT->ACC', 'CAT->TTA', 'CAT->TTG',
    'CAT->TTC', 'CAT->TGG', 'CAT->TGC', 'CAT->TCA', 'CAT->TCG', 'CAT->TCC', 'CAT->GTA', 'CAT->GTG', 'CAT->GTC', 'CAT->GGA',
    'CAT->GGG', 'CAT->GGC', 'CAT->GCA', 'CAT->GCG', 'CAT->GCC', 'CAC->ATA', 'CAC->ATT', 'CAC->ATG', 'CAC->AGA', 'CAC->AGT',
    'CAC->AGG', 'CAC->ACA', 'CAC->ACT', 'CAC->ACG', 'CAC->TTA', 'CAC->TTT', 'CAC->TTG', 'CAC->TGT', 'CAC->TGG', 'CAC->TCA',
    'CAC->TCT', 'CAC->TCG', 'CAC->GTA', 'CAC->GTT', 'CAC->GTG', 'CAC->GGA', 'CAC->GGT', 'CAC->GGG', 'CAC->GCA', 'CAC->GCT',
    'CAC->GCG', 'CAA->ATT', 'CAA->ATG', 'CAA->ATC', 'CAA->AGT', 'CAA->AGG', 'CAA->AGC', 'CAA->ACT', 'CAA->ACG', 'CAA->ACC',
    'CAA->TTT', 'CAA->TTG', 'CAA->TTC', 'CAA->TGT', 'CAA->TGG', 'CAA->TGC', 'CAA->TCT', 'CAA->TCG', 'CAA->TCC', 'CAA->GTT',
    'CAA->GTG', 'CAA->GTC', 'CAA->GGT', 'CAA->GGG', 'CAA->GGC', 'CAA->GCT', 'CAA->GCG', 'CAA->GCC', 'CAG->ATA', 'CAG->ATT',
    'CAG->ATC', 'CAG->AGA', 'CAG->AGT', 'CAG->AGC', 'CAG->ACA', 'CAG->ACT', 'CAG->ACC', 'CAG->TTA', 'CAG->TTT', 'CAG->TTC',
    'CAG->TGT', 'CAG->TGC', 'CAG->TCA', 'CAG->TCT', 'CAG->TCC', 'CAG->GTA', 'CAG->GTT', 'CAG->GTC', 'CAG->GGA', 'CAG->GGT',
    'CAG->GGC', 'CAG->GCA', 'CAG->GCT', 'CAG->GCC', 'CGT->AAA', 'CGT->AAG', 'CGT->AAC', 'CGT->ATA', 'CGT->ATG', 'CGT->ATC',
    'CGT->ACA', 'CGT->ACG', 'CGT->ACC', 'CGT->TAC', 'CGT->TTA', 'CGT->TTG', 'CGT->TTC', 'CGT->TCA', 'CGT->TCG', 'CGT->TCC',
    'CGT->GAA', 'CGT->GAG', 'CGT->GAC', 'CGT->GTA', 'CGT->GTG', 'CGT->GTC', 'CGT->GCA', 'CGT->GCG', 'CGT->GCC', 'CGC->AAA',
    'CGC->AAT', 'CGC->AAG', 'CGC->ATA', 'CGC->ATT', 'CGC->ATG', 'CGC->ACA', 'CGC->ACT', 'CGC->ACG', 'CGC->TAT', 'CGC->TTA',
    'CGC->TTT', 'CGC->TTG', 'CGC->TCA', 'CGC->TCT', 'CGC->TCG', 'CGC->GAA', 'CGC->GAT', 'CGC->GAG', 'CGC->GTA', 'CGC->GTT',
    'CGC->GTG', 'CGC->GCA', 'CGC->GCT', 'CGC->GCG', 'CGA->AAT', 'CGA->AAG', 'CGA->AAC', 'CGA->ATT', 'CGA->ATG', 'CGA->ATC',
    'CGA->ACT', 'CGA->ACG', 'CGA->ACC', 'CGA->TAT', 'CGA->TAC', 'CGA->TTT', 'CGA->TTG', 'CGA->TTC', 'CGA->TCT', 'CGA->TCG',
    'CGA->TCC', 'CGA->GAT', 'CGA->GAG', 'CGA->GAC', 'CGA->GTT', 'CGA->GTG', 'CGA->GTC', 'CGA->GCT', 'CGA->GCG', 'CGA->GCC',
    'CGG->AAA', 'CGG->AAT', 'CGG->AAC', 'CGG->ATA', 'CGG->ATT', 'CGG->ATC', 'CGG->ACA', 'CGG->ACT', 'CGG->ACC', 'CGG->TAT',
    'CGG->TAC', 'CGG->TTA', 'CGG->TTT', 'CGG->TTC', 'CGG->TCA', 'CGG->TCT', 'CGG->TCC', 'CGG->GAA', 'CGG->GAT', 'CGG->GAC',
    'CGG->GTA', 'CGG->GTT', 'CGG->GTC', 'CGG->GCA', 'CGG->GCT', 'CGG->GCC', 'ATT->TAC', 'ATT->TGG', 'ATT->TGC', 'ATT->TCA',
    'ATT->TCG', 'ATT->TCC', 'ATT->GAA', 'ATT->GAG', 'ATT->GAC', 'ATT->GGA', 'ATT->GGG', 'ATT->GGC', 'ATT->GCA', 'ATT->GCG',
    'ATT->GCC', 'ATT->CAA', 'ATT->CAG', 'ATT->CAC', 'ATT->CGA', 'ATT->CGG', 'ATT->CGC', 'ATT->CCA', 'ATT->CCG', 'ATT->CCC',
    'ATC->TAT', 'ATC->TGT', 'ATC->TGG', 'ATC->TCA', 'ATC->TCT', 'ATC->TCG', 'ATC->GAA', 'ATC->GAT', 'ATC->GAG', 'ATC->GGA',
    'ATC->GGT', 'ATC->GGG', 'ATC->GCA', 'ATC->GCT', 'ATC->GCG', 'ATC->CAA', 'ATC->CAT', 'ATC->CAG', 'ATC->CGA', 'ATC->CGT',
    'ATC->CGG', 'ATC->CCA', 'ATC->CCT', 'ATC->CCG', 'ATA->TAT', 'ATA->TAC', 'ATA->TGT', 'ATA->TGG', 'ATA->TGC', 'ATA->TCT',
    'ATA->TCG', 'ATA->TCC', 'ATA->GAT', 'ATA->GAG', 'ATA->GAC', 'ATA->GGT', 'ATA->GGG', 'ATA->GGC', 'ATA->GCT', 'ATA->GCG',
    'ATA->GCC', 'ATA->CAT', 'ATA->CAG', 'ATA->CAC', 'ATA->CGT', 'ATA->CGG', 'ATA->CGC', 'ATA->CCT', 'ATA->CCG', 'ATA->CCC',
    'ATG->TAT', 'ATG->TAC', 'ATG->TGT', 'ATG->TGC', 'ATG->TCA', 'ATG->TCT', 'ATG->TCC', 'ATG->GAA', 'ATG->GAT', 'ATG->GAC',
    'ATG->GGA', 'ATG->GGT', 'ATG->GGC', 'ATG->GCA', 'ATG->GCT', 'ATG->GCC', 'ATG->CAA', 'ATG->CAT', 'ATG->CAC', 'ATG->CGA',
    'ATG->CGT', 'ATG->CGC', 'ATG->CCA', 'ATG->CCT', 'ATG->CCC', 'ACT->TAC', 'ACT->TTA', 'ACT->TTG', 'ACT->TTC', 'ACT->TGG',
    'ACT->TGC', 'ACT->GAA', 'ACT->GAG', 'ACT->GAC', 'ACT->GTA', 'ACT->GTG', 'ACT->GTC', 'ACT->GGA', 'ACT->GGG', 'ACT->GGC',
    'ACT->CAA', 'ACT->CAG', 'ACT->CAC', 'ACT->CTA', 'ACT->CTG', 'ACT->CTC', 'ACT->CGA', 'ACT->CGG', 'ACT->CGC', 'ACC->TAT',
    'ACC->TTA', 'ACC->TTT', 'ACC->TTG', 'ACC->TGT', 'ACC->TGG', 'ACC->GAA', 'ACC->GAT', 'ACC->GAG', 'ACC->GTA', 'ACC->GTT',
    'ACC->GTG', 'ACC->GGA', 'ACC->GGT', 'ACC->GGG', 'ACC->CAA', 'ACC->CAT', 'ACC->CAG', 'ACC->CTA', 'ACC->CTT', 'ACC->CTG',
    'ACC->CGA', 'ACC->CGT', 'ACC->CGG', 'ACA->TAT', 'ACA->TAC', 'ACA->TTT', 'ACA->TTG', 'ACA->TTC', 'ACA->TGT', 'ACA->TGG',
    'ACA->TGC', 'ACA->GAT', 'ACA->GAG', 'ACA->GAC', 'ACA->GTT', 'ACA->GTG', 'ACA->GTC', 'ACA->GGT', 'ACA->GGG', 'ACA->GGC',
    'ACA->CAT', 'ACA->CAG', 'ACA->CAC', 'ACA->CTT', 'ACA->CTG', 'ACA->CTC', 'ACA->CGT', 'ACA->CGG', 'ACA->CGC', 'ACG->TAT',
    'ACG->TAC', 'ACG->TTA', 'ACG->TTT', 'ACG->TTC', 'ACG->TGT', 'ACG->TGC', 'ACG->GAA', 'ACG->GAT', 'ACG->GAC', 'ACG->GTA',
    'ACG->GTT', 'ACG->GTC', 'ACG->GGA', 'ACG->GGT', 'ACG->GGC', 'ACG->CAA', 'ACG->CAT', 'ACG->CAC', 'ACG->CTA', 'ACG->CTT',
    'ACG->CTC', 'ACG->CGA', 'ACG->CGT', 'ACG->CGC', 'AAT->TTA', 'AAT->TTG', 'AAT->TTC', 'AAT->TGG', 'AAT->TGC', 'AAT->TCA',
    'AAT->TCG', 'AAT->TCC', 'AAT->GTA', 'AAT->GTG', 'AAT->GTC', 'AAT->GGA', 'AAT->GGG', 'AAT->GGC', 'AAT->GCA', 'AAT->GCG',
    'AAT->GCC', 'AAT->CTA', 'AAT->CTG', 'AAT->CTC', 'AAT->CGA', 'AAT->CGG', 'AAT->CGC', 'AAT->CCA', 'AAT->CCG', 'AAT->CCC',
    'AAC->TTA', 'AAC->TTT', 'AAC->TTG', 'AAC->TGT', 'AAC->TGG', 'AAC->TCA', 'AAC->TCT', 'AAC->TCG', 'AAC->GTA', 'AAC->GTT',
    'AAC->GTG', 'AAC->GGA', 'AAC->GGT', 'AAC->GGG', 'AAC->GCA', 'AAC->GCT', 'AAC->GCG', 'AAC->CTA', 'AAC->CTT', 'AAC->CTG',
    'AAC->CGA', 'AAC->CGT', 'AAC->CGG', 'AAC->CCA', 'AAC->CCT', 'AAC->CCG', 'AAA->TTT', 'AAA->TTG', 'AAA->TTC', 'AAA->TGT',
    'AAA->TGG', 'AAA->TGC', 'AAA->TCT', 'AAA->TCG', 'AAA->TCC', 'AAA->GTT', 'AAA->GTG', 'AAA->GTC', 'AAA->GGT', 'AAA->GGG',
    'AAA->GGC', 'AAA->GCT', 'AAA->GCG', 'AAA->GCC', 'AAA->CTT', 'AAA->CTG', 'AAA->CTC', 'AAA->CGT', 'AAA->CGG', 'AAA->CGC',
    'AAA->CCT', 'AAA->CCG', 'AAA->CCC', 'AAG->TTA', 'AAG->TTT', 'AAG->TTC', 'AAG->TGT', 'AAG->TGC', 'AAG->TCA', 'AAG->TCT',
    'AAG->TCC', 'AAG->GTA', 'AAG->GTT', 'AAG->GTC', 'AAG->GGA', 'AAG->GGT', 'AAG->GGC', 'AAG->GCA', 'AAG->GCT', 'AAG->GCC',
    'AAG->CTA', 'AAG->CTT', 'AAG->CTC', 'AAG->CGA', 'AAG->CGT', 'AAG->CGC', 'AAG->CCA', 'AAG->CCT', 'AAG->CCC', 'AGT->TAC',
    'AGT->TTA', 'AGT->TTG', 'AGT->TTC', 'AGT->TCA', 'AGT->TCG', 'AGT->TCC', 'AGT->GAA', 'AGT->GAG', 'AGT->GAC', 'AGT->GTA',
    'AGT->GTG', 'AGT->GTC', 'AGT->GCA', 'AGT->GCG', 'AGT->GCC', 'AGT->CAA', 'AGT->CAG', 'AGT->CAC', 'AGT->CTA', 'AGT->CTG',
    'AGT->CTC', 'AGT->CCA', 'AGT->CCG', 'AGT->CCC', 'AGC->TAT', 'AGC->TTA', 'AGC->TTT', 'AGC->TTG', 'AGC->TCA', 'AGC->TCT',
    'AGC->TCG', 'AGC->GAA', 'AGC->GAT', 'AGC->GAG', 'AGC->GTA', 'AGC->GTT', 'AGC->GTG', 'AGC->GCA', 'AGC->GCT', 'AGC->GCG',
    'AGC->CAA', 'AGC->CAT', 'AGC->CAG', 'AGC->CTA', 'AGC->CTT', 'AGC->CTG', 'AGC->CCA', 'AGC->CCT', 'AGC->CCG', 'AGA->TAT',
    'AGA->TAC', 'AGA->TTT', 'AGA->TTG', 'AGA->TTC', 'AGA->TCT', 'AGA->TCG', 'AGA->TCC', 'AGA->GAT', 'AGA->GAG', 'AGA->GAC',
    'AGA->GTT', 'AGA->GTG', 'AGA->GTC', 'AGA->GCT', 'AGA->GCG', 'AGA->GCC', 'AGA->CAT', 'AGA->CAG', 'AGA->CAC', 'AGA->CTT',
    'AGA->CTG', 'AGA->CTC', 'AGA->CCT', 'AGA->CCG', 'AGA->CCC', 'AGG->TAT', 'AGG->TAC', 'AGG->TTA', 'AGG->TTT', 'AGG->TTC',
    'AGG->TCA', 'AGG->TCT', 'AGG->TCC', 'AGG->GAA', 'AGG->GAT', 'AGG->GAC', 'AGG->GTA', 'AGG->GTT', 'AGG->GTC', 'AGG->GCA',
    'AGG->GCT', 'AGG->GCC', 'AGG->CAA', 'AGG->CAT', 'AGG->CAC', 'AGG->CTA', 'AGG->CTT', 'AGG->CTC', 'AGG->CCA', 'AGG->CCT',
    'AGG->CCC', 'GTT->AAA', 'GTT->AAG', 'GTT->AAC', 'GTT->AGA', 'GTT->AGG', 'GTT->AGC', 'GTT->ACA', 'GTT->ACG', 'GTT->ACC',
    'GTT->TAC', 'GTT->TGG', 'GTT->TGC', 'GTT->TCA', 'GTT->TCG', 'GTT->TCC', 'GTT->CAA', 'GTT->CAG', 'GTT->CAC', 'GTT->CGA',
    'GTT->CGG', 'GTT->CGC', 'GTT->CCA', 'GTT->CCG', 'GTT->CCC', 'GTC->AAA', 'GTC->AAT', 'GTC->AAG', 'GTC->AGA', 'GTC->AGT',
    'GTC->AGG', 'GTC->ACA', 'GTC->ACT', 'GTC->ACG', 'GTC->TAT', 'GTC->TGT', 'GTC->TGG', 'GTC->TCA', 'GTC->TCT', 'GTC->TCG',
    'GTC->CAA', 'GTC->CAT', 'GTC->CAG', 'GTC->CGA', 'GTC->CGT', 'GTC->CGG', 'GTC->CCA', 'GTC->CCT', 'GTC->CCG', 'GTA->AAT',
    'GTA->AAG', 'GTA->AAC', 'GTA->AGT', 'GTA->AGG', 'GTA->AGC', 'GTA->ACT', 'GTA->ACG', 'GTA->ACC', 'GTA->TAT', 'GTA->TAC',
    'GTA->TGT', 'GTA->TGG', 'GTA->TGC', 'GTA->TCT', 'GTA->TCG', 'GTA->TCC', 'GTA->CAT', 'GTA->CAG', 'GTA->CAC', 'GTA->CGT',
    'GTA->CGG', 'GTA->CGC', 'GTA->CCT', 'GTA->CCG', 'GTA->CCC', 'GTG->AAA', 'GTG->AAT', 'GTG->AAC', 'GTG->AGA', 'GTG->AGT',
    'GTG->AGC', 'GTG->ACA', 'GTG->ACT', 'GTG->ACC', 'GTG->TAT', 'GTG->TAC', 'GTG->TGT', 'GTG->TGC', 'GTG->TCA', 'GTG->TCT',
    'GTG->TCC', 'GTG->CAA', 'GTG->CAT', 'GTG->CAC', 'GTG->CGA', 'GTG->CGT', 'GTG->CGC', 'GTG->CCA', 'GTG->CCT', 'GTG->CCC',
    'GCT->AAA', 'GCT->AAG', 'GCT->AAC', 'GCT->ATA', 'GCT->ATG', 'GCT->ATC', 'GCT->AGA', 'GCT->AGG', 'GCT->AGC', 'GCT->TAC',
    'GCT->TTA', 'GCT->TTG', 'GCT->TTC', 'GCT->TGG', 'GCT->TGC', 'GCT->CAA', 'GCT->CAG', 'GCT->CAC', 'GCT->CTA', 'GCT->CTG',
    'GCT->CTC', 'GCT->CGA', 'GCT->CGG', 'GCT->CGC', 'GCC->AAA', 'GCC->AAT', 'GCC->AAG', 'GCC->ATA', 'GCC->ATT', 'GCC->ATG',
    'GCC->AGA', 'GCC->AGT', 'GCC->AGG', 'GCC->TAT', 'GCC->TTA', 'GCC->TTT', 'GCC->TTG', 'GCC->TGT', 'GCC->TGG', 'GCC->CAA',
    'GCC->CAT', 'GCC->CAG', 'GCC->CTA', 'GCC->CTT', 'GCC->CTG', 'GCC->CGA', 'GCC->CGT', 'GCC->CGG', 'GCA->AAT', 'GCA->AAG',
    'GCA->AAC', 'GCA->ATT', 'GCA->ATG', 'GCA->ATC', 'GCA->AGT', 'GCA->AGG', 'GCA->AGC', 'GCA->TAT', 'GCA->TAC', 'GCA->TTT',
    'GCA->TTG', 'GCA->TTC', 'GCA->TGT', 'GCA->TGG', 'GCA->TGC', 'GCA->CAT', 'GCA->CAG', 'GCA->CAC', 'GCA->CTT', 'GCA->CTG',
    'GCA->CTC', 'GCA->CGT', 'GCA->CGG', 'GCA->CGC', 'GCG->AAA', 'GCG->AAT', 'GCG->AAC', 'GCG->ATA', 'GCG->ATT', 'GCG->ATC',
    'GCG->AGA', 'GCG->AGT', 'GCG->AGC', 'GCG->TAT', 'GCG->TAC', 'GCG->TTA', 'GCG->TTT', 'GCG->TTC', 'GCG->TGT', 'GCG->TGC',
    'GCG->CAA', 'GCG->CAT', 'GCG->CAC', 'GCG->CTA', 'GCG->CTT', 'GCG->CTC', 'GCG->CGA', 'GCG->CGT', 'GCG->CGC', 'GAT->ATA',
    'GAT->ATG', 'GAT->ATC', 'GAT->AGA', 'GAT->AGG', 'GAT->AGC', 'GAT->ACA', 'GAT->ACG', 'GAT->ACC', 'GAT->TTA', 'GAT->TTG',
    'GAT->TTC', 'GAT->TGG', 'GAT->TGC', 'GAT->TCA', 'GAT->TCG', 'GAT->TCC', 'GAT->CTA', 'GAT->CTG', 'GAT->CTC', 'GAT->CGA',
    'GAT->CGG', 'GAT->CGC', 'GAT->CCA', 'GAT->CCG', 'GAT->CCC', 'GAC->ATA', 'GAC->ATT', 'GAC->ATG', 'GAC->AGA', 'GAC->AGT',
    'GAC->AGG', 'GAC->ACA', 'GAC->ACT', 'GAC->ACG', 'GAC->TTA', 'GAC->TTT', 'GAC->TTG', 'GAC->TGT', 'GAC->TGG', 'GAC->TCA',
    'GAC->TCT', 'GAC->TCG', 'GAC->CTA', 'GAC->CTT', 'GAC->CTG', 'GAC->CGA', 'GAC->CGT', 'GAC->CGG', 'GAC->CCA', 'GAC->CCT',
    'GAC->CCG', 'GAA->ATT', 'GAA->ATG', 'GAA->ATC', 'GAA->AGT', 'GAA->AGG', 'GAA->AGC', 'GAA->ACT', 'GAA->ACG', 'GAA->ACC',
    'GAA->TTT', 'GAA->TTG', 'GAA->TTC', 'GAA->TGT', 'GAA->TGG', 'GAA->TGC', 'GAA->TCT', 'GAA->TCG', 'GAA->TCC', 'GAA->CTT',
    'GAA->CTG', 'GAA->CTC', 'GAA->CGT', 'GAA->CGG', 'GAA->CGC', 'GAA->CCT', 'GAA->CCG', 'GAA->CCC', 'GAG->ATA', 'GAG->ATT',
    'GAG->ATC', 'GAG->AGA', 'GAG->AGT', 'GAG->AGC', 'GAG->ACA', 'GAG->ACT', 'GAG->ACC', 'GAG->TTA', 'GAG->TTT', 'GAG->TTC',
    'GAG->TGT', 'GAG->TGC', 'GAG->TCA', 'GAG->TCT', 'GAG->TCC', 'GAG->CTA', 'GAG->CTT', 'GAG->CTC', 'GAG->CGA', 'GAG->CGT',
    'GAG->CGC', 'GAG->CCA', 'GAG->CCT', 'GAG->CCC', 'GGT->AAA', 'GGT->AAG', 'GGT->AAC', 'GGT->ATA', 'GGT->ATG', 'GGT->ATC',
    'GGT->ACA', 'GGT->ACG', 'GGT->ACC', 'GGT->TAC', 'GGT->TTA', 'GGT->TTG', 'GGT->TTC', 'GGT->TCA', 'GGT->TCG', 'GGT->TCC',
    'GGT->CAA', 'GGT->CAG', 'GGT->CAC', 'GGT->CTA', 'GGT->CTG', 'GGT->CTC', 'GGT->CCA', 'GGT->CCG', 'GGT->CCC', 'GGC->AAA',
    'GGC->AAT', 'GGC->AAG', 'GGC->ATA', 'GGC->ATT', 'GGC->ATG', 'GGC->ACA', 'GGC->ACT', 'GGC->ACG', 'GGC->TAT', 'GGC->TTA',
    'GGC->TTT', 'GGC->TTG', 'GGC->TCA', 'GGC->TCT', 'GGC->TCG', 'GGC->CAA', 'GGC->CAT', 'GGC->CAG', 'GGC->CTA', 'GGC->CTT',
    'GGC->CTG', 'GGC->CCA', 'GGC->CCT', 'GGC->CCG', 'GGA->AAT', 'GGA->AAG', 'GGA->AAC', 'GGA->ATT', 'GGA->ATG', 'GGA->ATC',
    'GGA->ACT', 'GGA->ACG', 'GGA->ACC', 'GGA->TAT', 'GGA->TAC', 'GGA->TTT', 'GGA->TTG', 'GGA->TTC', 'GGA->TCT', 'GGA->TCG',
    'GGA->TCC', 'GGA->CAT', 'GGA->CAG', 'GGA->CAC', 'GGA->CTT', 'GGA->CTG', 'GGA->CTC', 'GGA->CCT', 'GGA->CCG', 'GGA->CCC',
    'GGG->AAA', 'GGG->AAT', 'GGG->AAC', 'GGG->ATA', 'GGG->ATT', 'GGG->ATC', 'GGG->ACA', 'GGG->ACT', 'GGG->ACC', 'GGG->TAT',
    'GGG->TAC', 'GGG->TTA', 'GGG->TTT', 'GGG->TTC', 'GGG->TCA', 'GGG->TCT', 'GGG->TCC', 'GGG->CAA', 'GGG->CAT', 'GGG->CAC',
    'GGG->CTA', 'GGG->CTT', 'GGG->CTC', 'GGG->CCA', 'GGG->CCT', 'GGG->CCC',
    ]

no_stop_codon_deletion_table_list = ['-TTT', '-TTC', '-TTA', '-TTG', '-TCT', '-TCC', '-TCA', '-TCG', '-TAT', '-TAC',
                                     '-TGT', '-TGC', '-TGG', '-CTT', '-CTC', '-CTA', '-CTG', '-CCT', '-CCC', '-CCA',
                                     '-CCG', '-CAT', '-CAC', '-CAA', '-CAG', '-CGT', '-CGC', '-CGA', '-CGG', '-ATT',
                                     '-ATC', '-ATA', '-ATG', '-ACT', '-ACC', '-ACA', '-ACG', '-AAT', '-AAC', '-AAA',
                                     '-AAG', '-AGT', '-AGC', '-AGA', '-AGG', '-GTT', '-GTC', '-GTA', '-GTG', '-GCT',
                                     '-GCC', '-GCA', '-GCG', '-GAT', '-GAC', '-GAA', '-GAG', '-GGT', '-GGC', '-GGA',
                                     '-GGG']

no_stop_codon_addition_table_list = ['+TTT', '+TTC', '+TTA', '+TTG', '+TCT', '+TCC', '+TCA', '+TCG', '+TAT', '+TAC',
                                     '+TGT', '+TGC', '+TGG', '+CTT', '+CTC', '+CTA', '+CTG', '+CCT', '+CCC', '+CCA',
                                     '+CCG', '+CAT', '+CAC', '+CAA', '+CAG', '+CGT', '+CGC', '+CGA', '+CGG', '+ATT',
                                     '+ATC', '+ATA', '+ATG', '+ACT', '+ACC', '+ACA', '+ACG', '+AAT', '+AAC', '+AAA',
                                     '+AAG', '+AGT', '+AGC', '+AGA', '+AGG', '+GTT', '+GTC', '+GTA', '+GTG', '+GCT',
                                     '+GCC', '+GCA', '+GCG', '+GAT', '+GAC', '+GAA', '+GAG', '+GGT', '+GGC', '+GGA',
                                     '+GGG']

no_stop_mut_table_list = { 1  : no_stop_codon_mutation_table_list,
                           2  : no_stop_codon_2_internal_mutations_table_list,
                           3  : no_stop_codon_3_internal_mutations_table_list,
                          '-' : no_stop_codon_deletion_table_list,
                          '+' : no_stop_codon_addition_table_list}

